### ISSUE TITLE
unreadable part (CSS issue)

### ISSUE THREAD

**Issue by pw374** [ocsigen/ocsigen.github.io#41]
http://ocsigen.org/home/intro.html

<img width="1059" alt="screen shot 2019-01-19 at 8 45 04 am" src="https://user-images.githubusercontent.com/3776012/51429783-06522780-1bc7-11e9-9a06-90e9faf4b075.png">

**Comment by pw374** [comment]
<img width="1086" alt="screen shot 2019-01-19 at 8 51 20 am" src="https://user-images.githubusercontent.com/3776012/51429804-6648ce00-1bc7-11e9-8f5d-e9a0e4ccfa4d.png">

Holy shh...

**Comment by pw374** [comment]
<img width="1070" alt="screen shot 2019-01-19 at 8 57 37 am" src="https://user-images.githubusercontent.com/3776012/51429867-482f9d80-1bc8-11e9-92a9-3fc34ef2b653.png">
Oh, there's the same issue later on the page... It might be in several other places then

**Comment by pw374** [comment]
something like that might solve it:

```css
@media (min-width: 721px) {
.horiz-blocks>p:nth-child(2n) {
  margin-left: 1ex;
}
.horiz-blocks>p:nth-child(2n+1) {
  margin-right: 1ex;
}
}
```
